added more bash styles, tests, readmes, osx fixes, rmate updates

diff --git a/home/.matrix/opt/rmate-bash b/home/.matrix/opt/rmate-bash
--- a/home/.matrix/opt/rmate-bash
+++ b/home/.matrix/opt/rmate-bash
@@ -1,18 +1,18 @@
 #!/usr/bin/env bash
 
 # rmate
-# Copyright (C) 2011-2014 by Harald Lapp <harald@octris.org>
-# 
+# Copyright (C) 2011-2019 by Harald Lapp <harald@octris.org>
+#
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
-# 
+#
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
-# 
+#
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
@@ -27,15 +27,18 @@
 #
 
 #
-# Thanks very much to all users and contributors! All bug-reports, 
+# Thanks very much to all users and contributors! All bug-reports,
 # feature-requests, patches, etc. are greatly appreciated! :-)
 #
 
 # init
-# 
+#
+version="1.0.2"
+version_date="2019-04-08"
+version_string="rmate-sh $version ($version_date)"
 
 # determine hostname
-function hostname_command {
+function hostname_command(){
     if command -v hostname >/dev/null 2>&1; then
         echo "hostname"
     else {
@@ -54,16 +57,17 @@ hostname=$($(hostname_command))
 # default configuration
 host=localhost
 port=52698
+eval home=$(builtin printf "~%q" "${SUDO_USER:-$LOGNAME}")
 
 function load_config {
     local rc_file=$1
     local row
-    
+
     local host_pattern="^host(:[[:space:]]+|=)([^ ]+)"
     local port_pattern="^port(:[[:space:]]+|=)([0-9]+)"
-    
+
     if [ -f "$rc_file" ]; then
-        while read row; do
+        while read -r row; do
             if [[ "$row" =~ $host_pattern ]]; then
                 host=${BASH_REMATCH[2]}
             elif [[ "$row" =~ $port_pattern ]]; then
@@ -73,22 +77,19 @@ function load_config {
     fi
 }
 
-for i in "/etc/${0##*/}" ~/."${0##*/}.rc"; do
+for i in "/etc/${0##*/}" $home/."${0##*/}/${0##*/}.rc" $home/."${0##*/}.rc"; do
     load_config $i
 done
 
 host="${RMATE_HOST:-$host}"
 port="${RMATE_PORT:-$port}"
 
-if [[ "$host" = "auto" && "$SSH_CONNECTION" != "" ]]; then
-    host=${SSH_CONNECTION%% *}
-fi
 
 # misc initialization
-filepath=""
-selection=""
-displayname=""
-filetype=""
+filepaths=()
+displaynames=()
+selections=()
+filetypes=()
 verbose=false
 nowait=true
 force=false
@@ -96,17 +97,22 @@ force=false
 # process command-line parameters
 #
 function showusage {
-    echo "usage: $0 [-H host-name] [-p port-number] [-w] [-l line-number] [-m display-name] [-t file-type] [-f] [-v] file-path
+    echo "usage: $(basename $0) [arguments] [--] file-path  edit specified file
+   or: $(basename $0) [arguments] -          read text from stdin
 
--H  connect to host (default: $host)
--p  port number to use for connection (default: $port)
--w  wait for file to be closed by TextMate
--l  place caret on line number after loading file
--m  the display name shown in TextMate
--t  treat file as having specified type
--f  open even if file is not writable
--v  verbose logging messages
--h  display this usage information
+-H, --host HOST  Connect to HOST. Use 'auto' to detect the host from
+                 SSH. Defaults to $host.
+-p, --port PORT  Port number to use for connection. Defaults to $port.
+-w, --[no-]wait  Wait for file to be closed by TextMate.
+-l, --line LINE  Place caret on line number after loading file.
++N               Alias for --line, if N is a number (eg.: +5).
+-m, --name NAME  The display name shown in TextMate.
+-t, --type TYPE  Treat file as having specified type.
+-n, --new        Open in a new window (Sublime Text).
+-f, --force      Open even if file is not writable.
+-v, --verbose    Verbose logging messages.
+-h, --help       Display this usage information.
+    --version    Show version and exit.
 "
 }
 
@@ -117,96 +123,232 @@ function log {
 }
 
 function dirpath {
-  (cd `dirname $1`; pwd -P)
+    (cd "$(dirname "$1")" >/dev/null 2>/dev/null || { echo "unable to cd to $1 directory" 1>&2; exit; } ; pwd -P)
+}
+
+function resolvepath {
+    local filepath="$1"
+    local directory
+
+    while [ -L "$filepath" ]; do
+        directory="$(cd -P "$(dirname "$filepath")" && pwd)"
+        filepath="$(readlink "$filepath")"
+
+        if [[ "${filepath:0:1}" != "/" ]]; then
+            filepath="$directory/$filepath"
+        fi
+    done
+
+    echo "$filepath"
 }
 
 function canonicalize {
-    filepath="$1"
-    dir=`dirpath "$filepath"`
+    local filepath="$1"
+    local relativepath
+    local result
+
+    if [[ "${filepath:0:1}" = "-" ]]; then
+        filepath="./$filepath"
+    fi
+
+    local dir=$(dirpath "$filepath")
+
     if [ -L "$filepath" ]; then
-        relativepath=`cd "$dir"; readlink \`basename "$filepath"\``
-        result=`dirpath "$relativepath"`/`basename "$relativepath"`
+        relativepath=$(cd "$dir" || { echo "unable to cd to $dir" 1>&2; exit; } ; resolvepath "$(basename "$filepath")")
+        result=$(dirpath "$relativepath")/$(basename "$relativepath")
     else
-        result=`basename "$filepath"`
+        result=$(basename "$filepath")
         if [ "$dir" = '/' ]; then
             result="$dir$result"
         else
             result="$dir/$result"
         fi
     fi
-    echo $result
+
+    echo "$result"
 }
 
-while getopts H:p:wl:m:t:fvh OPTIONS; do
-    case $OPTIONS in
-        H)
-            host=$OPTARG;;
-        p)
-            port=$OPTARG;;
-        w) 
-            nowait=false;;
-        l)
-            selection=$OPTARG;;
-        m)
-            displayname=$OPTARG;;
-        t)
-            filetype=$OPTARG;;
-        f)
-            force=true;;
-        v)
-            verbose=true;;
-        h)
+while [[ "$1" != "" ]]; do
+    case $1 in
+        -)
+            filepaths+=("-")
+            ;;
+        --)
+            shift
+            break
+            ;;
+        -H|--host)
+            host=$2
+            shift
+            ;;
+        -p|--port)
+            port=$2
+            shift
+            ;;
+        -w|--wait)
+            nowait=false
+            ;;
+        --no-wait)
+            nowait=true
+            ;;
+        -l|--line)
+            selections+=($2)
+            shift
+            ;;
+        -m|--name)
+            displaynames+=($2)
+            shift
+            ;;
+        -t|--type)
+            filetypes+=($2)
+            shift
+            ;;
+        -n|--new)
+            new=true
+            ;;
+        -f|--force)
+            force=true
+            ;;
+        -v|--verbose)
+            verbose=true
+            ;;
+        --version)
+            echo "$version_string"
+            exit 0
+            ;;
+        -h|-\?|--help)
             showusage
-            exit 1;;
-        ?)
-            showusage
-            exit 1;;
+            exit 0
+            ;;
+        +[0-9][0-9]*)
+            selections+=(${1:1})
+            ;;
         *)
-            showusage
-            exit 1;;
+            if [[ "${1:0:1}" = "-" ]]; then
+                showusage
+                exit 1
+            else
+                filepaths+=("$1")
+            fi
+            ;;
     esac
+
+    shift
 done
 
-shift $((${OPTIND}-1))
-filepath="$1"
-
-if [ "$filepath" = "" ]; then
-    showusage
-    exit 1
+if [[ "$host" = "auto" && "$SSH_CONNECTION" != "" ]]; then
+    host=${SSH_CONNECTION%% *}
 fi
 
-shift
-if [ ! "${#@}" -eq 0 ]; then
-    echo "There are more than one files specified. Opening only $filepath and ignoring other."
-fi
+filepaths=("${filepaths[@]}" "$@")
 
-realpath=`canonicalize "$filepath"`
-echo $realpath
-
-if [ -f "$realpath" ] && [ ! -w "$realpath" ]; then
-    if [[ $force = false ]]; then
-        echo "File $filepath is not writable! Use -f to open anyway."
-        exit 1
-    elif [[ $verbose = true ]]; then
-        log "File $filepath is not writable! Opening anyway."
+if [ "${filepaths[*]}" = "" ]; then
+    if [[ $nowait = false ]]; then
+        filepaths=('-')
+    else
+        case "$-" in
+            *i*)
+                showusage
+                exit 1
+                ;;
+            *)
+                filepaths=('-')
+                ;;
+        esac
     fi
 fi
 
-if [ "$displayname" = "" ]; then
-    displayname="$hostname:$filepath"
-fi
 
 #------------------------------------------------------------
 # main
 #------------------------------------------------------------
+
+function open_file {
+    local index="$1"
+    local filepath="${filepaths[$index]}"
+    local selection="${selections[$index]}"
+    local filetype="${filetypes[$index]}"
+    local displayname="${displaynames[$index]}"
+    local realpath
+    local data
+
+    if [ "$filepath" != "-" ]; then
+        realpath=$(canonicalize "$filepath")
+        log "$realpath"
+
+        if [ -d "$filepath" ]; then
+            echo "$filepath is a directory and rmate is unable to handle directories."
+            exit 1
+        fi
+
+        if [ -f "$realpath" ] && [ ! -w "$realpath" ]; then
+            if [[ $force = false ]]; then
+                echo "File $filepath is not writable! Use -f to open anyway."
+                exit 1
+            elif [[ $verbose = true ]]; then
+                log "File $filepath is not writable! Opening anyway."
+            fi
+        fi
+
+        if [ "$displayname" = "" ]; then
+            displayname="$hostname:$filepath"
+        fi
+    else
+        displayname="$hostname:untitled"
+    fi
+
+    echo "open" 1>&3
+    echo "display-name: $displayname" 1>&3
+    echo "real-path: $realpath" 1>&3
+    echo "data-on-save: yes" 1>&3
+    echo "re-activate: yes" 1>&3
+    echo "token: $filepath" 1>&3
+
+    if [[ $new = true ]]; then
+        echo "new: yes"  1>&3
+    fi
+
+    if [ "$selection" != "" ]; then
+        echo "selection: $selection" 1>&3
+    fi
+
+    if [ "$filetype" != "" ]; then
+        echo "file-type: $filetype" 1>&3
+    fi
+
+    if [ "$filepath" != "-" ] && [ -f "$filepath" ]; then
+        filesize=$(($(wc -c <"$realpath")))
+        echo "data: $filesize" 1>&3
+        cat "$realpath" 1>&3
+    elif [ "$filepath" = "-" ]; then
+        if [ -t 0 ]; then
+            echo "Reading from stdin, press ^D to stop"
+        else
+            log "Reading from stdin"
+        fi
+
+        # preserve trailing newlines
+        data=$(cat; echo x)
+        data=${data%x}
+        filesize=$(($(echo -ne "$data" | wc -c)))
+        echo "data: $filesize" 1>&3
+        echo -n "$data" 1>&3
+    else
+        echo "data: 0" 1>&3
+    fi
+
+    echo 1>&3
+}
+
 function handle_connection {
     local cmd
     local name
     local value
     local token
     local tmp
-    
-    while read 0<&3; do
+    local content
+
+    while read -r 0<&3; do
         REPLY="${REPLY#"${REPLY%%[![:space:]]*}"}"
         REPLY="${REPLY%"${REPLY##*[![:space:]]}"}"
 
@@ -215,18 +357,18 @@ function handle_connection {
         token=""
         tmp=""
 
-        while read 0<&3; do
+        while read -r 0<&3; do
             REPLY="${REPLY#"${REPLY%%[![:space:]]*}"}"
             REPLY="${REPLY%"${REPLY##*[![:space:]]}"}"
 
             if [ "$REPLY" = "" ]; then
                 break
             fi
-            
+
             name="${REPLY%%:*}"
             value="${REPLY##*:}"
             value="${value#"${value%%[![:space:]]*}"}"      # fix textmate syntax highlighting: "
-                        
+
             case $name in
                 "token")
                     token=$value
@@ -236,7 +378,7 @@ function handle_connection {
                         tmp="/tmp/rmate.$RANDOM.$$"
                         touch "$tmp"
                     fi
-                
+
                     dd bs=1 count=$value <&3 >>"$tmp" 2>/dev/null
                     ;;
                 *)
@@ -246,54 +388,40 @@ function handle_connection {
 
         if [[ "$cmd" = "close" ]]; then
             log "Closing $token"
+            if [[ "$token" == "-" ]]; then
+                echo -n "$content"
+            fi
         elif [[ "$cmd" = "save" ]]; then
             log "Saving $token"
-
-            cat "$tmp" >  "$token"
-            rm "$tmp"       
+            if [ "$token" != "-" ]; then
+                cat "$tmp" > "$token"
+            else
+                content=$(cat "$tmp")
+            fi
+            rm "$tmp"
         fi
     done
-    
+
     log "Done"
 }
 
 # connect to textmate and send command
 #
-exec 3<> /dev/tcp/$host/$port
+exec 3<> "/dev/tcp/$host/$port"
 
 if [ $? -gt 0 ]; then
     echo "Unable to connect to TextMate on $host:$port"
     exit 1
 fi
 
-read server_info 0<&3
+read -r server_info 0<&3
 
 log $server_info
 
-echo "open" 1>&3
-echo "display-name: $displayname" 1>&3
-echo "real-path: $realpath" 1>&3
-echo "data-on-save: yes" 1>&3
-echo "re-activate: yes" 1>&3
-echo "token: $filepath" 1>&3
+for i in "${!filepaths[@]}"; do
+    open_file "$i"
+done
 
-if [ "$selection" != "" ]; then
-    echo "selection: $selection" 1>&3
-fi
-
-if [ "$filetype" != "" ]; then
-    echo "file-type: $filetype" 1>&3
-fi
-
-if [ -f "$filepath" ]; then
-    filesize=`ls -lL "$realpath" | awk '{print $5}'`
-    echo "data: $filesize" 1>&3
-    cat "$realpath" 1>&3
-else
-    echo "data: 0" 1>&3
-fi
-
-echo 1>&3
 echo "." 1>&3
 
 if [[ $nowait = true ]]; then
@@ -302,4 +430,3 @@ if [[ $nowait = true ]]; then
 else
     handle_connection
 fi
-
