Update core_utilities

diff --git a/home/.matrix/functions/core_utilities b/home/.matrix/functions/core_utilities
--- a/home/.matrix/functions/core_utilities
+++ b/home/.matrix/functions/core_utilities
@@ -24,3 +24,11 @@ function coreutil_check {
 }
 
 
+function mr_check {
+	command -v mr >/dev/null 2>&1
+ 
+	if [ $? -eq 1 ]; then
+	   echo -e "${YELLOW} MR git bundle manager is missing. Install 'mr'. ${NORMAL}"
+	   echo -e "${YELLOW} Run: 'cd ~ && mr -j5 update ' ${NORMAL}"
+	fi
+}  
